spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true   #输出到控制台
      database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: warn
    com.irm.blog: info
  file: log/bolg.log

server:
   port: 8090